### ISSUE TITLE
Support a Tagged.Set?

### ISSUE THREAD

**Issue by michaeljones** [joneshf/elm-tagged#3]
Thanks for writing this! I think I would definitely benefit from using using it in my code base. I have lots of typed ids and quite a few wrappers for the Dict & Set interfaces. 

Do you think it would be appropriate to support a Tagged.Set implementation as well? I think it suffers from the same problem that custom Ids and Dicts suffer from so it seems reasonable? Happy to try to add an implementation if it would be desirable.

**Comment by joneshf** [comment]
Yep! Go for it!

**Comment by joneshf** [comment]
Closing since #4 was merged, but feel free to reopen if there's still more you'd like to discuss.

**Comment by michaeljones** [comment]
Great :) Thanks! I appreciate the speedy release too. I'll let you know if I encounter any issues.
